[package]
name = "DadOS"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort" # Desativa o desempilhamento em caso de panic

[profile.release]
panic = "abort" # Desativa o desempilhamento em caso de panic

